data_ingestion:
  test_size: 0.20

model_training:
  n_estimators: 100
  learning_rate: 0.1
  max_depth: 6
  subsample: 0.8
  colsample_bytree: 0.8
  gamma: 0
  reg_lambda: 1
  reg_alpha: 0
  objective: "binary:logistic"
  eval_metric: "logloss"
  n_jobs: -1
  random_state: 42




# data_ingestion:
#   test_size: 0.20


# model_training:
#   n_estimators: 40
#   random_state: 42