name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if (Test-Path "D:/online foof feedback/online-food-feedback/requirements.txt") {pip install -r D:/online foof feedback/online-food-feedback/requirements.txt}
        pip install pandas scikit-learn numpy dvclive PyYAML pytest


    - name: Install DVC
      run: |
        pip install dvc

    - name: Reproduce DVC pipeline
      run: |
        if (Test-Path "D:/online foof feedback/online-food-feedback/src/_test.py") {pytest D:/online foof feedback/online-food-feedback/src/_test.py}
        